/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#00285d',
        'on-tertiary': '#00315d',
        'on-tertiary-fixed-variant': '#004883',
        'inverse-primary': '#005ac2',
        'on-surface': '#e2e2e9',
        'surface-tint': '#adc6ff',
        surface: '#111318',
        'surface-variant': '#33353a',
        'primary-container': '#4d8eff',
        'on-tertiary-container': '#002a51',
        'on-secondary-fixed-variant': '#3c475a',
        'error-container': '#93000a',
        'tertiary-fixed-dim': '#a4c9ff',
        'on-secondary-fixed': '#111c2d',
        'tertiary-container': '#4c93e7',
        'on-surface-variant': '#c2c6d6',
        'secondary-fixed-dim': '#bcc7de',
        'on-primary-fixed-variant': '#004395',
        'on-tertiary-fixed': '#001c39',
        'primary-fixed-dim': '#adc6ff',
        'on-secondary': '#263143',
        'on-primary-fixed': '#001a42',
        'secondary-fixed': '#d8e3fb',
        'surface-container-low': '#1a1b21',
        'outline-variant': '#424754',
        'surface-dim': '#111318',
        outline: '#8c909f',
        background: '#111318',
        'on-secondary-container': '#aeb9d0',
        secondary: '#bcc7de',
        primary: '#adc6ff',
        'surface-bright': '#37393f',
        'inverse-surface': '#e2e2e9',
        'inverse-on-surface': '#2e3036',
        'secondary-container': '#3e495d',
        'surface-container-high': '#282a2f',
        'surface-container-highest': '#33353a',
        tertiary: '#a4c9ff',
        'on-error-container': '#ffdad6',
        error: '#ffb4ab',
        'primary-fixed': '#d8e2ff',
        'on-error': '#690005',
        'on-background': '#e2e2e9',
        'surface-container-lowest': '#0c0e13',
        'tertiary-fixed': '#d4e3ff',
        'surface-container': '#1e2025',
        'on-primary': '#002e6a',
        'accent-blue': '#3B82F6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'stack-sm': '8px',
        'margin-mobile': '20px',
        'stack-lg': '32px',
        'container-max': '1280px',
        'stack-md': '16px',
        'margin-desktop': '48px',
        unit: '8px',
      },
      fontFamily: {
        headline: ['Sora', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        code: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        'code-sm': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
